#!/usr/bin/env bash


check_factor()
{
	if [ $# -ne 3 ];
        then
                given__args=("$@")
                counter=0
                number=1
                for a in ${given__args[*]};
                do
                        if [ $counter -gt 1 ];
                        then
                                number=$(echo $a*$number | bc)
                        fi
                        counter=$((counter + 1))
                done
        else
                number=$3
        fi

        otherNum=$2
        num=$(echo "$1" | tr ':' '=')

        final=$(echo "if($number > $otherNum) 1 else 0" | bc)
	        if ((final == 1)); then
		        numcp=$otherNum
		        otherNum=$number
		        number=$numcp
                fi

        echo "$num$otherNum*$number"
}

if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                final=$(factor "$i")
                check_factor $final

        done < "$1"
fi