#!/usr/bin/env bash
#is a nice challenge
check_factor()
{
	if [ $# -ne 3 ];
        then
                arguments=("$@")
                counter=0
                other=1
                for a in ${arguments[*]};
                do
                        if [ $counter -gt 1 ];
                        then
                                other=$(echo $a*$other | bc)
                        fi
                        counter=$((counter + 1))
                done
        else
                other=$3
        fi

        some=$2
        num=$(echo "$1" | tr ':' '=')

        result=$(echo "if($other > $some) 1 else 0" | bc)
	        if ((result == 1)); then
		        numcp=$some
		        some=$other
		        other=$numcp
                fi

        echo "$num$some*$other"
}

if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                result=$(factor "$i")
                check_factor $result

        done < "$1"
fi